baseURL: "https://benjameshughes.com"
title: Ben Hughes
paginate: 5
theme: PaperMod
enableEmoji: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Ben Hughes
  description: "My personal website. Filled with things I have learned and figured out. From web development to networking and everything else that makes computer and technology work"
  keywords: [Ben, Hughes, personal, html, css, docker, php, ci, cd, hardware, computers, tech, technology, blog, learn, teachings, tutorials]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Ben Hughes"
    # icon: /apple-touch-icon.png
    # iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Ben Hughes
    subtitle: "Learn, code, build"
    imageUrl: "img/me.jpeg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: Ben Hughes
    buttons:
      - name: Blog
        url: /blog/
      - name: Contact Me
        url: /contact/

  # home-info mode
  homeInfoParams:
    Title: "Welcome! \U0001F44B"
    # Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/benjameshughes"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: email
      url: "mailto:awkwardonesome@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: blog
      name: blog
      url: /blog/
      weight: 10
    - identifier: contact
      name: contact
      url: /contact/
      weight: 20
    - identifier: about me
      name: about
      url: /about/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai